### ISSUE TITLE
QueryResult 의 *sql.Rows 에 직접 접근할 방법을 제공한다

### ISSUE THREAD

**Issue by djinchung** [fatima-go/queryman#2]
**AS-IS**
Query 한 결과(result)의 경우 현재 Scan() 시에 구조체나 맵 형태로 처리가능하도록 제공하고 있다
하지만 결과에 대해서 column별 데이터를 커스텀하게 사용하고 싶을때 결과(*sql.Rows)에 직접 접근하는 방법이 없기에 현재로서는 불가능하다

**TO-BE**
QueryResult 구조체에 아래 함수를 추가 제공한다
```go
func (r *QueryResult) GetRows() *sql.Rows {
	return r.rows
}
```

**Comment by bestpop** [comment]
> 결과에 대해서 column별 데이터를 커스텀하게 사용하고 싶을때
어떤 경우인지를 예시를 들어 주면 이해하기 쉬울 것 같습니다.

**Comment by djinchung** [comment]
@bestpop 예를 들어 SHOW MASTER STATUS 같은 명령을 치면 
column, value 형태로 결과가 나오는데, 이때 column 들이 '정해지지 않았'기에.., 몇개의 필드가 나올지 모르는 상황에서는
미리 준비한 구조체로 매핑이 불가합니다.
이 경우 하나하나 받아서 (보통은) map 형태로 만들어 써야 합니다

**Comment by bestpop** [comment]
@djinchung 
```
mysql> SHOW MASTER STATUS\G
*************************** 1. row ***************************
             File: source-bin.000002
         Position: 1307
     Binlog_Do_DB: test
 Binlog_Ignore_DB: manual, mysql
Executed_Gtid_Set: 3E11FA47-71CA-11E1-9E33-C80AA9429562:1-5
1 row in set (0.00 sec)
```

위와 같은 형태일 때, `:` 를 기준으로 column:value 로 처리한다는 말씀이시군요?

잘 이해했습니다.

**Comment by djinchung** [comment]
@bestpop 아뇨..... 저건 CLI 에서 저렇게 프린트 한거예요~
